//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MY_Academy1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Tbl_Abouts
    {
        public int AboutId { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string CvUrl { get; set; }
        
        [NotMapped]  // Bu alan veritabanýna kaydedilmez
        public HttpPostedFileBase ImageFile { get; set; }
        [NotMapped]  // Bu alan veritabanýna kaydedilmez
        public HttpPostedFileBase CvFile { get; set; }
    }
}
